#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                  <aegis.z2h.dev>
#     .\_/.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis-workload-demo
  namespace: default
  labels:
    app.kubernetes.io/name: aegis-workload-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aegis-workload-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aegis-workload-demo
    spec:
      serviceAccountName: aegis-workload-demo
      containers:
      - name: main
        image: z2hdev/aegis-workload-demo-using-init-container:0.12.70
        env:
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: aegis-secret-aegis-workload-demo
                key: VALUE
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: aegis-secret-aegis-workload-demo
                key: USERNAME
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: aegis-secret-aegis-workload-demo
                key: PASSWORD

      initContainers:
      #
      # To make the init container exit successfully and initialize the main
      # container above, execute the following in Aegis Sentinel:
      #
      #   kubectl exec $sentinelPodName -n aegis-system -- aegis \
      #   -w aegis-workload-demo \
      #   -n default
      #   -s '{"username":"admin","password":"AegisRocks"}' \
      #   -t '{"USER":"{{.username}}", "PASS":"{{.password}}"}' \
      #   -k
      #
      # ☝️ this will create a Kubernetes `Secret` that the `main` container is
      # injecting as an environment variable and let the container consume
      # that `Secret`.
      #
      # -n : identifies the namespace of the Kubernetes `Secret`.
      # -k : means Aegis will update an associated Kubernetes Secret.
      # -t : will be used to transform the fields of the payload.
      #
      - name: init-container
        image: z2hdev/aegis-init-container:0.12.70
        volumeMounts:
        # Volume mount for SPIRE unix domain socket.
        - name: spire-agent-socket
          mountPath: /spire-agent-socket
          readOnly: true
        #
        # You can configure Aegis Init Container by providing environment 
        # variables.
        #
        # See https://aegis.z2h.dev/docs/configuration for more information
        # about these environment variables.
        #
        # When you don’t explicitly provide env vars here, Aegis Init Container
        # will assume the default values outlined in the given link above.
        #
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///spire-agent-socket/agent.sock"
        - name: AEGIS_LOG_LEVEL
          value: "6"
        - name: AEGIS_WORKLOAD_SVID_PREFIX
          value: "spiffe://aegis.z2h.dev/workload/"
        - name: AEGIS_SAFE_SVID_PREFIX
          value: "spiffe://aegis.z2h.dev/workload/aegis-safe/ns/aegis-system/sa/aegis-safe/n/"
        - name: AEGIS_INIT_CONTAINER_POLL_INTERVAL
          value: "5000"
      volumes:
      # Using SPIFFE CSI Driver to bind to the SPIRE Agent Socket
      # ref: https://github.com/spiffe/spiffe-csi
      - name: spire-agent-socket
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
